spring.application.name=sangsangseoga

#encoding
spring.mandatory-file-encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true

#database
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/sangsangseoga
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

#? value view
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#redis (Refresh Token 화이트리스트 저장소)
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}

#jwt
jwt.secret-key=${JWT_SECRET_KEY:defaultSecretKeySecretKeySecretKeySecretKeySecretKey}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=2592000000
